- Parse flag for decrypt - dycrypt test file

diff --git a/test b/test
--- a/test
+++ b/test
@@ -9,20 +9,34 @@ if test $# == 0; then
     exit 1
 fi
 
-echo -e "${CYAN}Encrypt data..."
 while [ "$1" ]; do
     echo -e "${GREEN}Test file: $1 ${NC}"
     for mode in ECB CBC CFB OFB CTR; do
+        echo -e "${CYAN}Encrypt data..."
+
+        filename=$(basename -- "${1}")
+        ex="${filename##*.}"
+
         ./encrypt.py -m $mode -i meocon $1 ./test_space/$1.encrypt.${mode} 
+        
         if test $? == 0; then
-            echo "[*] Run with $mode success"
+            echo "[*] Encrypt with $mode success"
         else
-            echo -e "[*] ${RED}Run with $mode failure${NC}"
+            echo -e "[*] ${RED}Encrypt with $mode failure${NC}"
         fi
+
+        echo -e "${CYAN}Decrypt data...${NC}"
+        ./decrypt.py -m $mode ./test_space/$1.encrypt.$mode ./test_space/$1.decrypt.$mode.$ex
+
+        if test $? == 0; then
+            echo "[*] Decrypt with $mode success"
+        else
+            echo -e "[*] ${RED}Decrypt with $mode failure${NC}"
+        fi
+
     done
     shift 1
 done
 
-echo -e "${CYAN}Encrypt data...${NC}"
 
-echo -e "${CYAN}Compare checksum...${NC}"
+# echo -e "${CYAN}Compare checksum...${NC}"
